### PR TITLE
fix(run): respect quiet/yes flags and handle prompt arguments

### LINKED ISSUE #738: [Bug]: 'run' command ignores '-q/--quiet' flag and remains interactive
### Describe the bug
When using the `run` subcommand with the quiet flag (e.g., `neovate run -q "show disk usage"`), the CLI still enters an interactive prompt and requires manual confirmation (Enter/Esc) before executing the generated command. This prevents the `run` command from being used effectively in non-interactive environments like CI/CD pipelines or headless scripts.

### Root Cause Analysis
Code analysis reveals two main issues:
1. **Control Flow in `src/index.ts`**: The `switch(command)` block for the `run` command executes `runRun(context)` and then returns `{}`, which prevents the execution from ever reaching the global `if (argv.quiet)` logic at the bottom of the `runNeovate` function.
2. **Hardcoded Interactivity in `src/commands/run.tsx`**: The `runRun` function is designed as a `while(true)` loop that always calls `askPrompt()` to get input and `confirmCommand()` to wait for a keypress, completely ignoring the `context.config.quiet` setting.

### Reproduction
Execute the following in a terminal:
```bash
neovate run -q "list all files"
```
**Actual Outcome**: The tool displays `dirname >` prompt or waits at `→ command [Enter/Esc]` for manual interaction.
**Expected Outcome**: The tool should generate the command and execute it (or display it based on desired headless behavior) without any blocking user interaction.

### Suggested Fix
- Update `src/index.ts` to pass the prompt and quiet flag correctly to the `run` command handler.
- Update `src/commands/run.tsx` to:
    - Support reading the prompt from command-line arguments.
    - Path logic to bypass `askPrompt` and `confirmCommand` when `quiet` mode is enabled.

### Environment
- **Version**: 0.27.0
- **Platform**: All (Windows/macOS/Linux)

### PR DESCRIPTION
**Pull request by kamusis**
### Description
Fixed issue #738 where the `run` command ignored the `-q/--quiet` flag and remained interactive. Additionally fixed a bug where prompt arguments (e.g., `neovate run "show disk usage"`) were being ignored and the tool would directly enter the interactive loop.

### Changes
- Updated `runRun` to parse `quiet`, `yes`, and `y` flags.
- Support `-y/--yes` as an alias for non-interactive execution.
- Extracted initial prompt from CLI arguments.
- Implemented single-shot execution logic for quiet/yes mode.
- In interactive mode, if a prompt is provided, skip the initial interactive prompt and proceed to generation/confirmation.
- Added a newline after confirmation for better UI.

Fixes #738

### CODE REVIEW

File: src/commands/run.tsx [hunk 1]
```diff
@@ -382,6 +413,8 @@ export async function runRun(context: Context) {
     const confirmed = await confirmCommand(rl, result.command);
     if (!confirmed) continue;
 
+    process.stdout.write('\n'); // Add newline after confirmation input
```
Comment (sorrycc) [inline src/commands/run.tsx]: don't add this, no newline after confirm is by design.

Comment (kamusis) [reply src/commands/run.tsx]: > don't add this, no newline after confirm is by design.

fixed
