### PR TITLE
fix: use expanded message content in user message display

### LINKED ISSUE #384: [Bug]: paste text don't work in slash command
### Describe the bug

.

### Reproduction

1. run slash command like `/spec/brainstorm` then paste a long text
2. the pasted text is not replaced

### Logs

```Shell

```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by xierenyuan**
close #384

### CODE REVIEW

File: src/ui/store.ts [hunk 1]
```diff
@@ -464,7 +464,7 @@ export const useAppStore = create<AppStore>()(
           if (commandeEntry) {
             const userMessage: Message = {
               role: 'user',
-              content: message, // Use original message with placeholders for display
+              content: expandedMessage, // Use original message with placeholders for display
```
Comment (sorrycc) [inline src/ui/store.ts]:
```suggestion
              content: expandedMessage,
```

**Review by sorrycc — APPROVED** [review]

**Review by sorrycc — APPROVED** [review]
